Name: release Process automation test

on:
  pull_request:

jobs:
  prepare_release:
    runs_on: 'ubuntu-latest'
    steps:
      - name: checkout head repo
        uses: actions/checkout@v3

      - name: checkout new tags to branches
        id: checkout-tags
        uses: chachako/checkout-tags@v1
        with:
          base: torvalds/linux

      - name: push to all new branches
        run: |
          while read branch; do
           ...
           git push origin $branch
          done <<< "${{ steps.checkout-tags.output.branches }}"